### ISSUE TITLE
Front page image (marko logo) uses wrong capitalization?

### ISSUE THREAD

**Issue by 0joshuaolson1** [marko-js/markojs-website#22]
'Marko' is used everywhere else.

**Comment by mlrawlings** [comment]
The lowercase logo is intentional, but in text, we capitalize "Marko."  We're certainly not the first brand to have capitalization in the logo different from how it is written in text (Facebook, Amazon, eBay, Citi, Airbnb, Intel, etc.).

If it makes you feel any better, any references to `marko` in code will be lowercase:
```bash
npm install marko
```

```js
import marko from "marko";
```

etc.

---

But yeah, the logo is lowercase and you should refer to it as "Marko" in normal text.  ¯\\\_(ツ)\_/¯

**Comment by 0joshuaolson1** [comment]
Facebook and Airbnb don't, but I didn't realize eBay does this.
